{"h": "Ggj2elVYNg==", "u": "https://stackoverflow.com/questions/3702675/catch-and-print-full-python-exception-traceback-without-halting-exiting-the-prog", "name": "Adam", "t": "2023-12-05 19:22:39.407178"}